security:
    role_hierarchy:
          ROLE_ADMIN: ROLE_USER
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
        MainBundle\Document\User:
            algorithm: bcrypt
            cost: 12
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    admin:
                        password: $2y$12$d3IbQjfvwXpBm27koJkZgeDG3HgWtMlSfsOm4dS2PjUm.r38ipIHC
                        roles: 'ROLE_ADMIN'
        user_db:
            id: my_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: main_login
                check_path: login_check
                default_target_path: profile
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/my, roles: ROLE_USER }
